[features]
seeds = false
skip-lint = false

[programs.localnet]
bank_simulator = "4QYK43nmFhCkckcSvr167fhYR2nYrVWKBMDdpWkD9PvT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/bolt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
clock = "clockwork localnet --bpf-program  4QYK43nmFhCkckcSvr167fhYR2nYrVWKBMDdpWkD9PvT ./tests/programs/metadata.so --bpf-program auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg ./tests/programs/rules.so"