[features]
seeds = false
skip-lint = false
[programs.localnet]
program = "5mP16ymxF7Ac2hw85oAzCJUUnu9deUvYTyWhaQ4M7H39"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/bolt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
